// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChmkn5PudQ0a06pZ1llLqoSmmZDNSrpkI',
    appId: '1:997821689958:web:311877b56e384430aa7da7',
    messagingSenderId: '997821689958',
    projectId: 'game-library-app-2f023',
    authDomain: 'game-library-app-2f023.firebaseapp.com',
    storageBucket: 'game-library-app-2f023.appspot.com',
    measurementId: 'G-6TV7BYFKF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJeYlwCPxhnbcsvvObHLdLy630u_hDBXI',
    appId: '1:997821689958:android:115849f7cda94ea1aa7da7',
    messagingSenderId: '997821689958',
    projectId: 'game-library-app-2f023',
    storageBucket: 'game-library-app-2f023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSqSDNaJ0ThhRqkuqfeeIaek4mIfoBk5I',
    appId: '1:997821689958:ios:6de82490fc3eafdeaa7da7',
    messagingSenderId: '997821689958',
    projectId: 'game-library-app-2f023',
    storageBucket: 'game-library-app-2f023.appspot.com',
    iosClientId: '997821689958-vu2fo4trl4h7isddsee47heo2u6v8d9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameLibraryApp',
  );
}
